name: Cleanup Dev Repo
jobs:
  Deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Aptly
        run: sudo apt-get update && sudo apt-get install aptly -y

      - name: Cleanup Database
        run: |
          # Removes unreferenced packages and pool files
          aptly db cleanup -config="repo/developy.aptly.conf" -dry-run -verbose
          
      - name: Remove Old Package Versions
        run: |
          aptly repo remove -config="repo/${branch}.aptly.conf" "${package}" '$Version (<< 4.1.0)' -dry-run