name: Clean Dev Repo

on:
  workflow_dispatch:

jobs:
  Deb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Aptly
        run: sudo apt-get update && sudo apt-get install aptly -y
        
      - name: Create config file
        run: |
          aptly repo create -config="repo/develop.aptly.conf" -distribution="${distro}" "${package}"

      - name: Cleanup Database
        run: |
          aptly db cleanup -config="repo/developy.aptly.conf" -dry-run -verbose
          
      - name: Remove Old Package Versions
        run: |
          aptly repo remove -config="repo/develop.aptly.conf" 'ombi, Version (<< 4.1.0)' -dry-run
